//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPACSViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPACSViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/annotation.png.
        /// </summary>
        internal static string annotationIcon {
            get {
                return ResourceManager.GetString("annotationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Annotation.
        /// </summary>
        internal static string annotationStr {
            get {
                return ResourceManager.GetString("annotationStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dcm.
        /// </summary>
        internal static string dicomExt {
            get {
                return ResourceManager.GetString("dicomExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/exit.png.
        /// </summary>
        internal static string exitIcon {
            get {
                return ResourceManager.GetString("exitIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit App.
        /// </summary>
        internal static string exitStr {
            get {
                return ResourceManager.GetString("exitStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Assets/instance.png.
        /// </summary>
        internal static string imageIcon {
            get {
                return ResourceManager.GetString("imageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/lung.png.
        /// </summary>
        internal static string lungIcon {
            get {
                return ResourceManager.GetString("lungIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to annotationModeChange.
        /// </summary>
        internal static string messageKey_annotationModeChange {
            get {
                return ResourceManager.GetString("messageKey_annotationModeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string messageKey_close {
            get {
                return ResourceManager.GetString("messageKey_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datasets.
        /// </summary>
        internal static string messageKey_datasets {
            get {
                return ResourceManager.GetString("messageKey_datasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detect.
        /// </summary>
        internal static string messageKey_detect {
            get {
                return ResourceManager.GetString("messageKey_detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string messageKey_file {
            get {
                return ResourceManager.GetString("messageKey_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        internal static string messageKey_folder {
            get {
                return ResourceManager.GetString("messageKey_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indexChange.
        /// </summary>
        internal static string messageKey_indexChange {
            get {
                return ResourceManager.GetString("messageKey_indexChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectedChange.
        /// </summary>
        internal static string messageKey_selectedChange {
            get {
                return ResourceManager.GetString("messageKey_selectedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to series.
        /// </summary>
        internal static string messageKey_series {
            get {
                return ResourceManager.GetString("messageKey_series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seriesIndex.
        /// </summary>
        internal static string messageKey_seriesIndex {
            get {
                return ResourceManager.GetString("messageKey_seriesIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seriesTotal.
        /// </summary>
        internal static string messageKey_seriesTotal {
            get {
                return ResourceManager.GetString("messageKey_seriesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        internal static string messageKey_status {
            get {
                return ResourceManager.GetString("messageKey_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/net.png.
        /// </summary>
        internal static string netIcon {
            get {
                return ResourceManager.GetString("netIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Series Description.
        /// </summary>
        internal static string noSeriesDescriptionStr {
            get {
                return ResourceManager.GetString("noSeriesDescriptionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICOM Files|*.dcm.
        /// </summary>
        internal static string openFileDialogFilter {
            get {
                return ResourceManager.GetString("openFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open DICOM File.
        /// </summary>
        internal static string openFileDialogTitle {
            get {
                return ResourceManager.GetString("openFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/file.png.
        /// </summary>
        internal static string openFileIcon {
            get {
                return ResourceManager.GetString("openFileIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string openFileStr {
            get {
                return ResourceManager.GetString("openFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets/folder.png.
        /// </summary>
        internal static string openFolderIcon {
            get {
                return ResourceManager.GetString("openFolderIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string openFolderStr {
            get {
                return ResourceManager.GetString("openFolderStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Assets/patient.png.
        /// </summary>
        internal static string patientIcon {
            get {
                return ResourceManager.GetString("patientIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string patientIDStr {
            get {
                return ResourceManager.GetString("patientIDStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        internal static string patientNameStr {
            get {
                return ResourceManager.GetString("patientNameStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query/Retrieve.
        /// </summary>
        internal static string QRStr {
            get {
                return ResourceManager.GetString("QRStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert All.
        /// </summary>
        internal static string revertAllStr {
            get {
                return ResourceManager.GetString("revertAllStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Assets/series.png.
        /// </summary>
        internal static string seriesIcon {
            get {
                return ResourceManager.GetString("seriesIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Original.
        /// </summary>
        internal static string showOriginalStr {
            get {
                return ResourceManager.GetString("showOriginalStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Assets/study.png.
        /// </summary>
        internal static string studyIcon {
            get {
                return ResourceManager.GetString("studyIcon", resourceCulture);
            }
        }
    }
}
